// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// greedy_cluster_cpp
Rcpp::List greedy_cluster_cpp(const arma::mat& x, const int& k, const int& nd, const bool& rngstart, const bool& greedy, const int& greedy_reset, const bool& greedy_end, const bool& competitive, const int& competitive_release, const arma::vec& lrange, const double& tol, const arma::vec& maxiter, const int& seed, const int& trace);
RcppExport SEXP _GKM_greedy_cluster_cpp(SEXP xSEXP, SEXP kSEXP, SEXP ndSEXP, SEXP rngstartSEXP, SEXP greedySEXP, SEXP greedy_resetSEXP, SEXP greedy_endSEXP, SEXP competitiveSEXP, SEXP competitive_releaseSEXP, SEXP lrangeSEXP, SEXP tolSEXP, SEXP maxiterSEXP, SEXP seedSEXP, SEXP traceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const int& >::type k(kSEXP);
    Rcpp::traits::input_parameter< const int& >::type nd(ndSEXP);
    Rcpp::traits::input_parameter< const bool& >::type rngstart(rngstartSEXP);
    Rcpp::traits::input_parameter< const bool& >::type greedy(greedySEXP);
    Rcpp::traits::input_parameter< const int& >::type greedy_reset(greedy_resetSEXP);
    Rcpp::traits::input_parameter< const bool& >::type greedy_end(greedy_endSEXP);
    Rcpp::traits::input_parameter< const bool& >::type competitive(competitiveSEXP);
    Rcpp::traits::input_parameter< const int& >::type competitive_release(competitive_releaseSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lrange(lrangeSEXP);
    Rcpp::traits::input_parameter< const double& >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< const int& >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const int& >::type trace(traceSEXP);
    rcpp_result_gen = Rcpp::wrap(greedy_cluster_cpp(x, k, nd, rngstart, greedy, greedy_reset, greedy_end, competitive, competitive_release, lrange, tol, maxiter, seed, trace));
    return rcpp_result_gen;
END_RCPP
}
// predict_cluster_cpp
std::vector<int> predict_cluster_cpp(const arma::mat& x, const arma::mat& centres, const arma::mat& minmax, const int& k);
RcppExport SEXP _GKM_predict_cluster_cpp(SEXP xSEXP, SEXP centresSEXP, SEXP minmaxSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type centres(centresSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type minmax(minmaxSEXP);
    Rcpp::traits::input_parameter< const int& >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(predict_cluster_cpp(x, centres, minmax, k));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_GKM_greedy_cluster_cpp", (DL_FUNC) &_GKM_greedy_cluster_cpp, 14},
    {"_GKM_predict_cluster_cpp", (DL_FUNC) &_GKM_predict_cluster_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_GKM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
