# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

is_connected_matrix_directed <- function(adj_matrix) {
    .Call('_GKM_is_connected_matrix_directed', PACKAGE = 'GKM', adj_matrix)
}

create_adjacency_list_regular <- function(k, neighbours) {
    .Call('_GKM_create_adjacency_list_regular', PACKAGE = 'GKM', k, neighbours)
}

create_adjacency_list_grid <- function(k) {
    .Call('_GKM_create_adjacency_list_grid', PACKAGE = 'GKM', k)
}

neighbourhood_reconstruction <- function(neighbourhood, k) {
    .Call('_GKM_neighbourhood_reconstruction', PACKAGE = 'GKM', neighbourhood, k)
}

greedy_cluster_cpp <- function(x, k, neighbourhood, rng_start, greedy, greedy_end, competitive, competitive_release, lrange, tol, maxiter, seed, trace) {
    .Call('_GKM_greedy_cluster_cpp', PACKAGE = 'GKM', x, k, neighbourhood, rng_start, greedy, greedy_end, competitive, competitive_release, lrange, tol, maxiter, seed, trace)
}

predict_cluster_cpp <- function(x, centres, minmax, k) {
    .Call('_GKM_predict_cluster_cpp', PACKAGE = 'GKM', x, centres, minmax, k)
}

