# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

greedy_cluster_cpp <- function(x, k, nd, rngstart, greedy, greedy_reset, greedy_end, competitive, competitive_release, lrange, tol, maxiter, seed, trace) {
    .Call('_GKM_greedy_cluster_cpp', PACKAGE = 'GKM', x, k, nd, rngstart, greedy, greedy_reset, greedy_end, competitive, competitive_release, lrange, tol, maxiter, seed, trace)
}

predict_cluster_cpp <- function(x, centres, minmax, k) {
    .Call('_GKM_predict_cluster_cpp', PACKAGE = 'GKM', x, centres, minmax, k)
}

